name: html validate

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: html5 validation
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
